# Generated by Django 5.2.1 on 2025-05-09 20:17

import auth_app.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0006_alter_post_wallpaper_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_wallpaper',
            name='image',
            field=models.ImageField(storage=auth_app.storage.MediaStorage(), upload_to='uploads/'),
        ),
    ]
